{"name": "test_read_user", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../db.json'", "trace": "self = <allure_test.TestUserCRUD object at 0x0000018EE8863B00>\n\n    @pytest.fixture(autouse=True)\n    def setup_and_teardown(self):\n        # Setup: create a unique user for each test\n        self.user_id = faker.uuid4()\n        self.user = User(self.user_id, faker.name(), faker.email())\n>       user_crud.create(self.user_id, self.user)\n\nallure_test.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \napi_test.py:79: in create\n    data = self.file_handler.read_data()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api_test.JSONHandler object at 0x0000018EE8861D90>\n\n    def read_data(self):\n>       with open(self.filename, 'r') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../db.json'\n\napi_test.py:65: FileNotFoundError"}, "start": 1703511136744, "stop": 1703511136744, "uuid": "f2e604e5-2d5c-4277-bfa6-edf4b49db4ea", "historyId": "9816c93f9f49f17f2ec0e0afc644d37f", "testCaseId": "9816c93f9f49f17f2ec0e0afc644d37f", "fullName": "allure_test.TestUserCRUD#test_read_user", "labels": [{"name": "story", "value": "Read User"}, {"name": "feature", "value": "User Operations"}, {"name": "suite", "value": "allure_test"}, {"name": "subSuite", "value": "TestUserCRUD"}, {"name": "host", "value": "DESKTOP-4HQA4QS"}, {"name": "thread", "value": "24960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_test"}]}