{"name": "test_create_user", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../db.json'", "trace": "self = <allure_test.TestUserCRUD object at 0x0000018EE8862E10>\n\n    @pytest.fixture(autouse=True)\n    def setup_and_teardown(self):\n        # Setup: create a unique user for each test\n        self.user_id = faker.uuid4()\n        self.user = User(self.user_id, faker.name(), faker.email())\n>       user_crud.create(self.user_id, self.user)\n\nallure_test.py:23: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \napi_test.py:79: in create\n    data = self.file_handler.read_data()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <api_test.JSONHandler object at 0x0000018EE8861D90>\n\n    def read_data(self):\n>       with open(self.filename, 'r') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: '../db.json'\n\napi_test.py:65: FileNotFoundError"}, "start": 1703511136627, "stop": 1703511136627, "uuid": "ba74e2e5-619a-4a7a-ba9e-a32fe3836e3d", "historyId": "4f58051a3ce6c0be925c386d1c90aac2", "testCaseId": "4f58051a3ce6c0be925c386d1c90aac2", "fullName": "allure_test.TestUserCRUD#test_create_user", "labels": [{"name": "story", "value": "Create User"}, {"name": "feature", "value": "User Operations"}, {"name": "suite", "value": "allure_test"}, {"name": "subSuite", "value": "TestUserCRUD"}, {"name": "host", "value": "DESKTOP-4HQA4QS"}, {"name": "thread", "value": "24960-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "allure_test"}]}