{"uuid": "a797533f-9734-4af8-8388-c457ad2a8fae", "children": ["ba74e2e5-619a-4a7a-ba9e-a32fe3836e3d"], "befores": [{"name": "setup_and_teardown", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../db.json'\n", "trace": "  File \"C:\\Users\\mikeo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mikeo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mikeo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mikeo\\Desktop\\testing_practica\\allure_test.py\", line 23, in setup_and_teardown\n    user_crud.create(self.user_id, self.user)\n  File \"C:\\Users\\mikeo\\Desktop\\testing_practica\\api_test.py\", line 79, in create\n    data = self.file_handler.read_data()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mikeo\\Desktop\\testing_practica\\api_test.py\", line 65, in read_data\n    with open(self.filename, 'r') as file:\n         ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1703511136670, "stop": 1703511136671}], "start": 1703511136670, "stop": 1703511136742}