{"uuid": "0c24cad4-d46b-46fc-9f3c-0eacd1c0501d", "children": ["faa56c7c-f6a6-4ed9-9d84-8e4ee992a4e7"], "befores": [{"name": "setup_and_teardown", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '../db.json'\n", "trace": "  File \"C:\\Users\\mikeo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mikeo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mikeo\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mikeo\\Desktop\\testing_practica\\allure_test.py\", line 23, in setup_and_teardown\n    user_crud.create(self.user_id, self.user)\n  File \"C:\\Users\\mikeo\\Desktop\\testing_practica\\api_test.py\", line 79, in create\n    data = self.file_handler.read_data()\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\mikeo\\Desktop\\testing_practica\\api_test.py\", line 65, in read_data\n    with open(self.filename, 'r') as file:\n         ^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1703511136765, "stop": 1703511136765}], "start": 1703511136765, "stop": 1703511136773}